### ISSUE TITLE
OAK-D crash with Face Detection.

### ISSUE THREAD

**Issue by HaroldPX** [luxonis/depthai-unity#44] opened 2023-11-06 14:39 UTC
Hi,
I have an OAK-D Pro Wide OV9782 Camera and I d'like to use it as head tracking.

I have tried OAK For Unity project  but it's not working as expected.

The first scene with Basic streams is working well but all other scenes (Body Pose or Face Detection) crash with a Runtime Error (error C++). I can't see any information in log.

An other point is Head Pose is not available. Any information about a release date ?

I am running on Windows 10 with Unity 2021.3.30f. Is there any drivers to add, security or project settings to set ?

Thanks,

**Comment by gespona** [comment] 2023-11-07 14:30
Hi @HaroldPX ,

I tested on my side and all examples are working fine with OAK-D-PRO-W 

Could you check editor log? You can access from console window -> three dots button -> open editor log 

Head pose demo is coming during this month.

Beside trying to use USB3 cables and USB3 ports, there is no major considerations to use out-of-the-box demos.

**Comment by HaroldPX** [comment] 2023-11-07 16:12
Hi @Gespona

I'm using the USB cable provided in the box on an USB3 port.

The scene FaceDetector crashes at line 145 DaiFaceDetector.cs :   deviceRunning = InitFaceDetector(config);

In the log, I have this warning : [1844301051F4980F00] [2.6] [0.678] [ColorCamera(0)] [warning] Unsupported resolution set for detected camera OV9782, needs 800_P or 720_P. Defaulting to 800_P
I tried to change rgbResolution to 800_P but I still have the warning and the crash.

Thanks,

**Comment by HaroldPX** [comment] 2023-11-07 16:35
For information face detection is working in DepthAI application.

**Comment by gespona** [comment] 2023-11-08 10:30
Hi, yes this error makes sense as sensor resolution is different. In fact you can see specific code to manage this resolution inside DaiFaceDetector.cs

if (rgbResolution == RGBResolution.THE_800_P)
            {
                config.ispScaleF1 = 1;
                config.ispScaleF2 = 2;
            }

It's important you change the resolution using the inspector like in this screenshot:

![image](https://github.com/luxonis/depthai-unity/assets/5397648/63d936b7-8c67-4a2c-9f7d-1a876dc4b95a)

**Comment by gespona** [comment] 2023-11-09 10:56
Set THE_800_P should be enough. Unity plugin is not detecting automatically with type of camera / sensor you connect, that's why you need to setup in inspector. The reason behind is the pipeline and use different resolutions and different ispScales.

So if I understand correctly, you set THE_800_P in the inspector, and still crashing right? Could you paste here the editor log?

**Comment by HaroldPX** [comment] 2023-11-09 11:17
I don't see anything in the log :
[Editor.log](https://github.com/luxonis/depthai-unity/files/13307361/Editor.log)

I also attached the config value before InitFaceDetector craches :
[Config](https://github.com/luxonis/depthai-unity/assets/150045653/74831ca7-5762-4087-a2e5-e7d26d171ca7)

Thanks

**Comment by gespona** [comment] 2023-11-09 11:38
I think I was able to reproduce the issue and found the root cause behind the lastest changes for letterbox preview. 

I created a new branch https://github.com/luxonis/depthai-unity/tree/fix-letterbox-wide    

The issue impacts only on face detector and body pose.

All that said, you still need to set THE_800_P in the inspector

Could you confirm that branch solves your issue?

**Comment by HaroldPX** [comment] 2023-11-09 12:47
It works !

**Comment by gespona** [comment] 2023-11-09 13:43
Cool ! I will improve the letterbox selection mode in the face detector example and then I will merge the branch . Closing this ticket. Reopen if need it

**Closed by gespona** 2023-11-09 13:43 UTC

**Comment by HaroldPX** [comment] 2024-02-19 10:38
Hi Gerard,

Sorry I sent you an email.
Did you merge this branch to the main branch ?
I tried to move to the main branch but I still have the same issue.

Thanks.
