### ISSUE TITLE
DepthAI Crashes on Pointclouds using OAK-D

### ISSUE THREAD

**Issue by morrowyn** [luxonis/depthai-unity#33] opened 2023-04-13 09:09 UTC
Hi, 

I'm trying the URP demo scenes. Everything works fine on windows apart from the pointcloud scenes. This one crashes after running for 30 seconds or so. I'm an oak-d.

Could this be to the fact that this device is not suitable for pointclouds, due to to lack of a time of flight module?

Here is the managed stacktrace:
```
=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
Received signal SIGSEGV
Obtained 17 stack frames
0x00007ff614934411 (Unity) WindowsVideoMedia::GetFirstReadyTextureTime
0x00007ff61593c566 (Unity) VideoMediaTextureOutput::ConsumeFrame
0x00007ff61491cd35 (Unity) VideoClipPlayback::GetTextureAtTimeInternal
0x00007ff614922db1 (Unity) VideoPlayback::GetTexture
0x00007ff614918fed (Unity) VideoPlayer::VideoUpdate
0x00007ff614918e3e (Unity) VideoManager::VideoUpdate
0x00007ff6149028fc (Unity) `InitializeVideoManagerCallbacks'::`2'::PreUpdateUpdateVideoRegistrator::Forward
0x00007ff613c45bda (Unity) ExecutePlayerLoop
0x00007ff613c45d66 (Unity) ExecutePlayerLoop
0x00007ff613c4be49 (Unity) PlayerLoop
0x00007ff614bbdab9 (Unity) PlayerLoopController::UpdateScene
0x00007ff614bbbc5b (Unity) Application::TickTimer
0x00007ff615010fba (Unity) MainMessageLoop
0x00007ff61501588b (Unity) WinMain
0x00007ff6163f315e (Unity) __scrt_common_main_seh
0x00007ff829597604 (KERNEL32) BaseThreadInitThunk
0x00007ff82b2626a1 (ntdll) RtlUserThreadStart
```

**Comment by gespona** [comment] 2023-04-13 17:16
Hi @morrowyn , if you use OAK-D should be fine, as we just need depth to generate point cloud. No need of ToF. The stack trace not showing issue on the plugin side, so could you share more details on how to reproduce the issue?

- Windows version
- Unity version
- Steps to reproduce the issue

**Comment by morrowyn** [comment] 2023-04-17 16:22
Windows 10 pro: 10.0.19045 Build 19045
Unity: 2021.3.22f1 LTS
Nvidia 1060gtx 6gb having latest drivers

Steps to reproduce are:
- Connect OAK-D
- Open project in URP directory
- Navigate to Point Cloud VFX or Point Cloud 2 VFX
- Let it run on itself
- After 30 seconds to 3 minute it crashes

**Comment by gespona** [comment] 2023-04-18 21:53
Hi ! I tested running for 5+ minutes and I'm not able to reproduce the crash.

One thing usually generates issues is the USB cable. Could you check you using USB3 cable?

I just updated repo with latest version of depthai-core. I don't think it's really relevant, but could you try again?

**Comment by gespona** [comment] 2023-05-08 10:58
@morrowyn any update on your side?

**Comment by morrowyn** [comment] 2023-05-08 12:20
Yes. I have tested it with different usb3 cables and on different windows machines. And I still receive that error on the pointcloud alone while the others scenes works as expected.

**Comment by gespona** [comment] 2023-05-11 15:40
> Yes. I have tested it with different usb3 cables and on different windows machines. And I still receive that error on the pointcloud alone while the others scenes works as expected.

It's very strange. Is it happening only on VFX or also happening on normal point cloud example?

**Comment by gespona** [comment] 2023-07-18 11:55
Hi @morrowyn , While I'm updating the repo and testing everything I think I'm able to reproduce similar issue, but only if connecting to USB slow port. If I'm using USB3 cable and connecting to proper fast USB port there is no issue.

Beside confirming you're using USB3 cable, could you confirm that you're connecting to fast USB port on PC?

**Comment by gespona** [comment] 2023-08-17 12:42
@morrowyn any chance to test?

**Comment by morrowyn** [comment] 2023-08-17 13:10
Heya, 
Sorry for the late reply. I have tested it with a USB3 gen 2 10gb/s cable and port. This yielded the same result in crashing the app. So either I have a faulty device, or there might be some driver playing up.

**Comment by gespona** [comment] 2023-08-22 15:36
@morrowyn  mmmmmm not sure what else we can do here, I guess you don't have any other device to test/compare. Recently I bumped depthai-core version, may help on "driver" side ....  did you tested with latest version of the repo?

**Comment by gespona** [comment] 2023-12-06 20:20
Closing this ticket. Reopen if needed.

**Closed by gespona** 2023-12-06 20:20 UTC
